### ISSUE TITLE
'cp' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by explainable-ai** [vietanhdev/hugo-curious#1]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [ ] Read the README.md
- [ ] Have the extended version of Hugo installed
- [ ] Used the exampleSite's config.toml as a reference

**Describe the bug**

A clear and concise description of what the bug is. [REPLACE]

This `cp -a themes/hugo-curious/exampleSite/* .` does not working for Windows 10.  Double checking if this is correct. 

**Desktop (please complete the following information):**
 Windows 10
 - Chrom

**Comment by vietanhdev** [comment]
Hello,
You can try the following solutions:
- Use: `cp -r themes/hugo-curious/exampleSite/* .`
- Use file manager (Explorer) to copy all the content that folder (`themes/hugo-curious/exampleSite/`) to the root folder of your site (the folder that contains `themes`).

**Comment by wbgreen0405** [comment]
Thank you. Great theme.

**Comment by explainable-ai** [comment]
Is this file no longer available? `_override.sass`
