### ISSUE TITLE
Icons not loading and 404 errors all over pages

### ISSUE THREAD

**Issue by sakumatto** [vietanhdev/hugo-curious#5]
I did all changes on the localhost and also put the `baseurl = "http://aqvitae.com"  # Include trailing slash`as should be. But after transfer to live site the icons are not loading even though they are in the path when I check. Also weirdly many 404 error per page where I presume the headings are and toc.

Any help would be greatly appreciated. The site is at http://aqvitae.com and the repo at https://github.com/sakumatto/kehitysliitto

**Comment by vietanhdev** [comment]
Hello,
Where did you deploy your site? Can you tell me more about the steps you've done?
I recommend Netlify for a free site builder and hosting service.

**Comment by sakumatto** [comment]
AFTER my last email I was able to establish that the changes in theme directory were not being reflected to the server. I copied the layout directory to the main hugo directory. This way I was able to fix the issue on the Netlify server.
